// mod print;
// mod variables;
// mod premitive;
// mod strings;
// mod array;
// mod tuples;
// mod vectors;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointers;
// mod structs;
// mod enums;
mod cli;
fn main() {
    println!("Hello, world!");
    // print::run();
    // variables::run();
    // premitive::run();
    // strings::run();
    // tuples::run();
    // array::run();
    // vectors::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointers::run();
    // structs::run();
    // enums::run();
    cli::run();
}
